DROP TABLE IF EXISTS brewery;

CREATE TABLE brewery (
    brewery_id serial,
    brewery_name varchar (50) NOT NULL, 
    website varchar(32) NOT NULL,
    phone varchar(16) NOT NULL,
    history varchar(10000) NOT NULL, 
    image varchar(200) NULL, 
    address varchar(200) NOT NULL, 
    days_and_hours_of_operation varchar(200) NOT NULL, 
    CONSTRAINT PK_brewery_id PRIMARY KEY(brewery_id)
    );
    
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (1, 'Urban Artifact', 'artifactbeer.com', '5135424222','At first glance, it might seem like Urban Artifact is having a bit of an identity crisis: It looks like a place of worship, sounds like a nightclub, smells like a restaurant, and ships away load after load of its canned beer. But the brewery, operating out of historic St. Patricks Church in Northside, has an identity that is so much more than its stellar fruit-forward sour beers. Theres its restaurant, Wildfire Pizza Kitchen; its radio station, Radio Artifact; its taproom (thats become a local-music mecca); its private event and outdoor spaces; and of course its brewery, which despite all the multitasking doesnt sacrifice an ounce of quality in its on-site and wholesale offerings', '1660 Blue Rock St., Northside', 'Wed 4-11pm, Thurs 4-11pm, Fri 4pm-12am');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (2, 'Fibonacci Brewing Company', 'fibbrew.com', '5138321422', 'Before long, sourced locally at Fibonacci will also mean right outside. The brewery has an on-site urban farm with an apiary, goats, chickens, and fruits and berries they plan to source for their beers, among them Pride of the Valley, a wheat ale with locally foraged paw paw fruit, and Mulberry Grove, a sour ale made with mulberries collected in a Fibonacci-run competition. Theres more to the story: Fibonacci also operates an Airbnb, so you can drink some beer, meet goats Fiddlehead and Honey, then cozy up in an old farmhouse for the night.', '1445 Compton Rd. Mt Healthy', 'Wed 5-10pm, Thurs 5-10pm, Fri 3-11pm, Sat 11-11pm, Sun 11am-8pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (3, 'Rhinegeist Brewery', 'rhinegeist.com', '5133811367', 'Since its birth in 2013 in the old Christian Moerlein bottling plant, Rhinegeist has gone from producing 2,000 barrels to 106,000 barrels in 2019. That makes it the second largest brewery in Cincinnati and Ohio by sales volume. All that growth also increases opportunities to give back. Local nonprofits can benefit from weekly charitable suds nights, and the annual MOVE event, when aerialists take over the taproom, supports Mission2Move, a group teaching mindful movement classes in an effort to prevent chronic stress. Great beer and giving back? Thats a platform we can get behind.', '1910 Elm St., Over-the-Rhine', 'Tues Wed Thurs 3-10pm, Fri Sat 12pm-12am, Sun 12-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (4, 'Darkness Brewing', 'darknessbrewing.beer.com', '8598158375', 'Those who embrace the dark side of the beer spectrum will find a home in this former garage in Northern Kentucky. Since Eric Bosler and Ron Sanders opened Darkness in 2016, its quickly become a neighborhood staple. A few lighter styles pop up among the stouts, porters, and brown ales on the menu, and theres always a cider available. A permanent food truck, Darkness Diner, claims space in the courtyard, and you can turn your Sunday into Funday with the weekly brunch.','224 Fairfield Ave., Bellevue', 'Mon 3-10pm, Tues 3-10pm Wed 3-10pm, Thurs 3-10pm, Fri 3pm-12am, Sat 12pm-12am, Sun 11am-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (5, 'Bircus Brewing Company', 'bircus.com', '8003818232', 'Founded by Paul Miller, an honest-to-God Ringling Bros. clown, Bircus (pronounced beer-cuss) opened in 2018 to help support Circus Mojo, a troupe of performers who make good use of the taprooms location in the historic Ludlow Theatre. Miller and his investors have plans to expand: The group purchased a former propane plant with Ohio River views and intends to convert it into a beer-centric event center (and a canning line for the brewery). Whos the clown now?', '322 Elm St., Ludlow', ' Tues Wed Thurs 4-10pm, Fri 4-1am, Sat 12-1am, Sun 12-8pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (6, 'Fifty West Brewing Company', 'fiftywestbrew.com', '5138348789', 'Lots of breweries host on-site workout classes, but Fifty West takes �exercising while drinking� to the next level with sand volleyball, running, cycling, and canoeing and kayaking programming at its Production Works location along the Little Miami Scenic Trail and Little Miami River. It also hosts Punch Out, an annual �brewery-on-brewery� boxing tournament, and plans to debut a fast-casual restaurant with a beer garden and futsal court in the former Pizelii space next month. To fuel its patrons� active lifestyles, it serves Quencher, a 100-calorie activated ale with electrolytes and reduced gluten. Plus, a seasonal menu at its Brewpub is inspired by its Flying Pig Marathon training programs.', '7668 U.S. Route 50, Columbia Twp', 'Mon Tues Wed Thurs 11-11pm, Fri Sat 11am-12am, Sun 11am-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (7, 'Brink Brewing Co', 'bringbrewking.com', '5138823334', 'Would you expect to find the country Very Small Brewing Company of the Year in College Hill? How about the back-to-back champion? That would be Brink, which took Great American Beer Festival medals in the Sweet/Cream Stout and English-Style Mild Ale categories for the second year in a row in 2019. The cozy, welcoming neighborhood brewpub is unassuming otherwise, with gleaming tanks in full view and old-fashioned board games in the bookcase.','5905 Hamilton Ave., College Hill', 'Mon Tues  Wed 3-10pm, Thurs 1-11pm, Fri 1-12am, Sat 12-12am, Sun 12-10pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (8, 'Fretboard Brewing Company', 'fretboardbrewing.com', '5139144677', 'This place hits all the right notes with an emphasis on live music three nights a week, plus open mic nights and flights delivered on a modified guitar neck. A second brewpub in downtown Hamilton offers full lunch and dinner menus and a rooftop patio overlooking the Great Miami River. Fretboard also uploads regular Spotify playlists created with customer input, from East Coast Hip-Hop to 80s One-Hit Wonders.', '5800 Creed Rd., Blue Ash', 'Mon Tues Wed Thurs 3-10pm, Fri Sat 12-12am');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (9, 'HighGrain Brewing Co', 'highgrainbrewing.com', '5137917000', 'Sustainability was top priority when the owners of HighGrain revitalized Silvertons former town hall into a brewery and restaurant. Its still a main focus: They purchase electricity from an Ohio wind farm, donate spent grain to farmers, and source ingredients locally. Most recently, brewer Matthew Utter released Lili Joey Pale Ale, a beer to benefit victims of the Australia wildfires, inviting other breweries to serve it up and contribute to this worthy cause.', '6860 Plainfield Rd., Silverton', 'Mon Tues Wed Thurs 3-10pm, Fri Sat 12-11pm, Sun 12-8pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (10, 'March First Brewing and Distilling', 'marchfirstbrewing.com', '5137189173', 'When this brewery registered with the state, it didn�t have a name, so as a placeholder, the owners used the date, March First. Once they discovered that Ohio became a state on that day in 1803, the name clicked. Theyve displayed a pioneering approach ever since, venturing into spirits, cider, and hard seltzer in addition to a full menu of craft beers. The large taproom features a pizza and sandwich kitchen, an outdoor patio, and specialty cocktails made with its own Cooper Island Rum, Sycamore Whiskey, and Voltage Vodka brands. You won�t run out of options here.', '7885 E. Kemper Rd., Sycamore Twp', 'Mon Tues Wed Thurs 1130-11, Fri Sat 1130-12am, Sun 1130-10pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (11, 'West Side Brewing', 'westsidebrewing.com', '5136612337', 'Its all the best parts of the west side under one roof, from a come as you are attitude to a no-nonsense beer menu of Amber Ale, Common Ale, Hefeweizen, Double IPA, and Session IPA. Nothing too cute. You�ll find yourself among running clubs warming up and/or cooling down, friends studying up for trivia night, and families fresh from the new Westwood Town Hall playground across the street. West is best, hun.', '3044 Harrison Ave., Westwood', 'Sun Mon Tues Wed Thurs 12-11pm, Fri 12-1am, Sat 11-1am');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (12, 'MadTree Brewing', 'madtreebrewing.com', '5138368733', 'If you�ve been a fan of MadTree since 2013, you remember its original Kennedy Avenue taproom, located about a mile from the much larger Madison Road facility it debuted in 2017. Now a community gathering spot and home to Oakley�s monthly flea market and Catch-A-Fire Pizza, MadTree continues to grow as Cincinnati�s third-largest brewery. It recently redesigned its cans and website and joined 1% For the Planet, an international organization whose members donate 1 percent of annual sales to nonprofits focused on environmental sustainability.', '3301 Madison Rd., Oakley', 'Mon Tues Wed Thurs 11-11pm, Fri 11-12am, Sat 10-12am, Sun 10-11pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (13, 'Rolling Mill Brewing Company', 'rollingmillbc.com', '5132174444', 'A celiac disease diagnosis left Josh Laubach unable to consume gluten, a protein found in wheat. That meant no more bread, pastries�or beer. But Josh and wife Megan jumped into action and, over time, learned the art of brewing beer, minus the gluten. In 2016 they turned that skill into Rolling Mill Brewing Company, a fully gluten-free brewery in the heart of Middletown. Unlike most GF beers, Rolling Mill�s IPAs, lagers, stouts, and other brews are made with grains that don�t contain gluten (rather than simply removing the gluten after brewing), meaning they�re safe for those avoiding gluten and those with celiac alike.', '916 First Ave., Middletown', 'Thurs 5-8pm, Fri 5-10pm, Sat 1-8pm, Sun 1-5pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (14, 'Listermann Brewing Company', 'listermannbrewing.com', '5137311130', 'Dan Listermann moved his home brewing supply shop to Dana Avenue in 1995, catering to weekend mash masters at that point, a very niche audience. In 2008, he decided to start producing suds for the general public, eventually adding a small tasting space next to the shop. Slowly, the taproom footprint has grown, and the beer lineup has evolved from the early days, when dark beers dominated (hello, Chickow), to experimental New England IPAs (hello, Team Fiona). Still, Listermann serves hobby brewers, selling kits that let you cook up your own version of its recipes.', '916 First Ave., Middletown', 'Mon Tues Wed Thurs 12-9pm, Fri Sat 12-10pm, Sun 12-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (15, 'Braxton Brewing Company', 'braxtonbrewing.com', '5132615600', 'You could say Braxton Brewing Company likes to break the mold. It crowd-funded $71,885 to construct its taproom, created the area�s first barrel-aging brewery and taproom, and built a $5 million rooftop space nearly five years after first opening. It also gets creative. Beyond staple offerings like Garage Beer lager, Revamp IPA, and Storm golden cream ale, Braxton also partners with companies to create new brews, such as Graeter�s Black Raspberry Chocolate Chip Stout and Buzz, the official beer of the Bunbury Music Festival.', '27 W. Seventh St., Covington', 'Mon Tues 3-10pm, Wed Thurs 11-10pm, Fri Sat 11-12am, Sun 11am-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (16, 'Big Ash Brewing', 'bigashbrewing.com', '5134016868', 'Nine years ago, Dave Emery and 25 of his �beer-minded buddies� invested $5,200 in brewing equipment and started making beer in the basement of his Anderson Township home. In September, after renovating a Mexican restaurant into a taproom and brewery and growing to almost 100 partners, the group unveiled Big Ash Brewing. The coolest part? A 28-tap self-serve tap wall with Big Ash beers, guest brews, and wine lets customers sample all they want (employees start pouring after 32 ounces) without bothering a bartender or holding up the line.', '5230 Beechmont Ave., Mt. Washington', 'Mon Tues Wed 4-10pm, Thurs Fri 4-12am, Sat 12-12am, Sun 12-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (17, 'Little Miami Brewing Company', 'littlemiamibrewing.com', '5137131121', 'Perched on the edge of the Little Miami River and Little Miami Scenic Trail in downtown Milford, this brewery screams outdoorsy. The river views from its patio and rooftop bar are unbeatable, and most of its beers are named after animals or things found in nature like Junkyard Dog, its global IPA, and Bike Path, its Bohemian Pilsner. And the brewery is just as fun to visit during the winter months. On a chilly Monday evening in February, the taproom was packed with families playing cards, groups prepping for trivia, and friends enjoying fresh made-in-house brick oven pizza.', '208 Mill St., Milford', 'Sun Mon 11-10pm, Tues Wed Thurs 11-11pm, Fri Sat 11-12am');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (18, 'Tafts Ale House', 'taftsbeer.com', '5133341393', 'Theres something special about being in Taft�s Ale House. Though the site has no direct ties to its namesake William H. Taft and theres no evidence he ever stepped foot in the building, its steeped in history. Constructed in 1850 as St. Pauls Evangelical Church said to be the oldest Protestant church building in the city it held congregations of Northern German immigrants until the church merged with a Westwood congregation in 1948. Following decades of abandoned renovation attempts, the brewery opened in 2015 after an exhaustive $9.6 million restoration. The drama of the space�s gothic arched windows, soaring tray ceilings, and overlooking mezzanine are unmatched. While three small tanks are visible where the altar once stood, almost all of the beer is brewed at its 50,000-square-foot brewpourium on Spring Grove Avenue.', '1429 Race St., Over-the-Rhine', 'Mon Tues Wed Thurs 1130-10pm, Fri Sat 1130-12am, Sun 1130-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (19, 'Streetside Brewery', 'streetsidebrewery.com', '5136155877', 'This cozy neighborhood joint is an under-the-radar fan favorite. Last fall it took top prize in Cincinnati Magazines Battle of the Breweries bracket. Its easy to see why: The lineup is diverse with IPAs, wheats, lagers, and fruity varieties, so theres something for everybody, and its damn good. If the stellar suds and charming vibe arent enough to get you in the door, the activities schedule will. About once a week, mosey over for beer pairings, crafting sessions, and trivia nights.', '4003 Eastern Ave., Columbia-Tusculum', 'Mon Tues Wed 12-10pm, Thurs Fri 11-11pm, Sat 10-11pm, Sun 10-9pm');
    INSERT INTO brewery (brewery_id, brewery_name, website, phone, history, address, days_and_hours_of_operation) 
    VALUES (20, '3 Points Urban Brewery', '3pointsbeer.com', '5139184804', 'Opened in 2018 by Hickory Wald, 3 Points is about more than just beer. Its founders wanted to create an outlet for local artists to showcase their work. And you cant help but feel a creative spark here: Each beer on the rotating tap list is paired with original artwork that serves as a visual representation of the beers tasting notes and of course, youre surrounded by all those murals. Get in good with the eclectic neighborhood folk and join the Wednesday Mug Club, where beer refills are $2 all day with purchase of a 3 Points mug.', '331 E. 13th St., Pendleton', 'Mon Tues 3-10pm, Wed Thurs 11-10pm, Fri Sat 11-12am, Sun 11-9pm');